### ISSUE TITLE
npm ERR! Unexpected end of JSON input while parsing near '...83e05832cc9","tarball'

### ISSUE THREAD

**Issue by ashishgupta1350** [DimitriMikadze/Mean-Blog#4]
While running npm install, I ran into this error. Any suggestions on how I can resolve this. A google search suggests that I should completely uninstall npm and node from windows 10, then reinstall it. I am not sure that all that trouble is required.

Here is the error. I used both cmd and git bash  with admin privileges.
$ npm install
npm WARN deprecated bcrypt@0.8.7: bcrypt < v2.0.0 is susceptible to bcrypt wrap-around bug. Upgrade to bcrypt >= v2.0.0 for improved support for newer bcrypt hashes
npm ERR! Unexpected end of JSON input while parsing near '...83e05832cc9","tarball'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\80LM0141IH\AppData\Roaming\npm-cache\_logs\2018-11-11T08_54_29_212Z-debug.log

**Comment by abbassiddiqi** [comment]
Cleaning the corrupted local npm cache may fix this error.

    npm cache clean --force

Just run your npm command again after executing the above command in your terminal.

----------

There could be few other reasons for the invalid JSON, as described in the official documentation [here](https://docs.npmjs.com/common-errors#invalid-json).

The official `npm` website has well documented most of the common errors. But unfortunately they don’t appear on the top results when you google the error.

**Comment by ashishgupta1350** [comment]
Thanks. It worked.
